### ISSUE TITLE
How to pass ejs options?

### ISSUE THREAD

**Issue by hasanbayatme** [jmjuanes/electron-ejs#7]
The options listed in ejs website: [EJS](http://ejs.co/) options section

**Comment by jmjuanes** [comment]
Hello @EmpireWorld, sorry for the delay. This feature will be available in `v1.1.0`. At the moment you can only pass variables to your ejs files. 

Please give me some days to finish it and I will publish the new version with this feature.

Thanks!

**Comment by hasanbayatme** [comment]
Thank you, i waiting for that!
If you need help call me.

**Comment by jmjuanes** [comment]
Hello! 
The version `v1.1.0` is now out. Now you can use ejs options: 

``` javascript
//Import module 
var electronEjs = require('electron-ejs'); 

//Initialize the render 
var ejs = new electronEjs({ /* your data */ }, { /* your options */ });
```

Please, try it and tell me if you have any problem or issue :)

**Comment by hasanbayatme** [comment]
There is no issue, all done, thanks :)
